language: cpp

os:
  - linux

# Use Ubuntu 16.04 LTS (Xenial) as the Linux testing environment.
dist: xenial
sudo: false

git:
  depth: 1

branches:
  only:
    - master
    - ocl-open-70
    - ocl-open-80
    - ocl-open-90

env:
  matrix:
    - BUILD_TYPE=Release
    - BUILD_TYPE=Debug

addons:
  apt:
    sources:
      - sourceline: 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-9 main'
        key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
      - ubuntu-toolchain-r-test
    packages:
      - llvm-9-tools
      - llvm-9-dev
      - libclang-9-dev

install:
  - git clone https://github.com/KhronosGroup/SPIRV-LLVM-Translator.git -b llvm_release_90 spirv-llvm-translator
  - mkdir spirv-llvm-translator/build && cd spirv-llvm-translator/build
  - cmake .. -DCMAKE_INSTALL_PREFIX=./install -DBUILD_SHARED_LIBS=ON -DLLVM_BUILD_TOOLS=ON -DCMAKE_BUILD_TYPE=${BUILD_TYPE}
  - make -j`nproc` && make install
  - cd ../../

compiler:
  - gcc
  - clang

script:
   # For some reason cmake expects lit-cpuid to be installed.
   # But llvm-9 packages in the current state do not provide it.
   # As a temporary workaround we create a dummy file just to pacify cmake.
  - sudo touch /usr/lib/llvm-9/bin/lit-cpuid
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DLLVM_NO_DEAD_STRIP=ON -DLLVMSPIRV_INCLUDED_IN_LLVM=OFF -DSPIRV_TRANSLATOR_DIR=${TRAVIS_BUILD_DIR}/spirv-llvm-translator/build/install -DCMAKE_INSTALL_PREFIX=./install ..
  - make -j`nproc` && make install
