language: cpp

os:
  - linux

# Use Ubuntu 16.04 LTS (Xenial) as the Linux testing environment.
dist: xenial

git:
  depth: 1
  quiet: true

branches:
  only:
    - master
    - ocl-open-70
    - ocl-open-80

env:
  matrix:
    - BUILD_TYPE=Release
    - BUILD_TYPE=Debug


install:
  - git clone https://github.com/llvm-mirror/llvm.git -b release_80
  - cd ./llvm/tools
  - git clone https://github.com/llvm-mirror/clang.git -b release_80
  - cd ../projects
  - git clone https://github.com/KhronosGroup/SPIRV-LLVM-Translator.git -b llvm_release_80 llvm-spirv
  - git clone https://github.com/intel/opencl-clang.git -b ocl-open-80
  - cd ../..

compiler:
  - gcc

script:
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DLLVM_NO_DEAD_STRIP=ON --DCMAKE_INSTALL_PREFIX=./install ../llvm
  - make -j`nproc`
